AssetStore/Models/Asset.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Drawing;
using System.ComponentModel.DataAnnotations;

namespace AssetStore.Models
{
    public class Asset
    {
        [Key]
        public int Id { get; set; }  //key
        [Required]
        public string Name { get; set; }
        [Required(ErrorMessage = "The description field is required")]
        [Display(Name = "Describe the asset briefly")]
        public string Description { get; set; }
        public string Publisher { get; set; }
        [Required(ErrorMessage = "Select platform")]
        public string Platform { get; set; }
        [Required(ErrorMessage = "The Price field is required")]
        [Display(Name = "Enter price in €")]
        public float Price { get; set; }
        public float Size { get; set; }  //in MB
        public string ReleaseDate { get; set; }
        [Required(ErrorMessage = "Select type of asset")]
        [Display(Name = "Type of Asset")]
        public string Type { get; set; }   //the type of asset
        public string imagesId { get; set; }
        public byte[] assetZip { get; set; }
    }
}

AssetStore/Controllers/AssetsController.cs
using AssetStore.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace AssetStore.Controllers
{
    public class AssetsController : Controller
    {
        private AssetsDbContext _context;

        private PictureDbContext _photoContext;

        private ItemDbContext _itemContext;

        public AssetsController() {
            _context = new AssetsDbContext();
            _photoContext = new PictureDbContext();
            _itemContext = new ItemDbContext();
        }
        [HttpGet]
        public ActionResult Index(string search) {
            AllAssets all = new AllAssets();
            if (search != null)
            {
                if (search.ToLower().Contains("2d"))
                {
                    all.assets2D = _context.Assets2D.ToList();
                }
                if (search.ToLower().Contains("3d"))
                {
                    all.assets3D = _context.Assets3D.ToList();
                }
                if (search.ToLower().Contains("tools"))
                {
                    all.assetsTools = _context.AssetsTools.ToList();
                }
                if (search.ToLower().Contains("audio"))
                {
                    all.assetsAudio = _context.AssetsAudio.ToList();
                }
                if (search.ToLower().Contains("free"))
                {
                    all.assets2D = _context.Assets2D.Where(z => z.Price == 0).ToList();
                    all.assets3D = _context.Assets3D.Where(z => z.Price == 0).ToList();
                    all.assetsAudio = _context.AssetsAudio.Where(z => z.Price == 0).ToList();
                    all.assetsTools = _context.AssetsTools.Where(z => z.Price == 0).ToList();
                }
                if (_context.Assets2D != null)
                {
                    foreach (var item in _context.Assets2D)
                    {
                        if (item.Name.Contains(search) && !all.assets2D.Contains(item))
                        {
                            all.assets2D.Add(item);
                        }
                    }
                }
                if (_context.Assets3D != null)
                {
                    foreach (var item in _context.Assets3D)
                    {
                        if (item.Name.Contains(search) && !all.assets3D.Contains(item))
                        {
                            all.assets3D.Add(item);
                        }
                    }
                    
                }
                if (_context.AssetsTools != null)
                {
                    foreach (var item in _context.AssetsTools)
                    {
                        if (item.Name.Contains(search) && !all.assetsTools.Contains(item))
                        {
                            all.assetsTools.Add(item);
                        }
                    }
                }
                if (_context.AssetsAudio != null)
                {
                    foreach (var item in _context.AssetsAudio)
                    {
                        if (item.Name.Contains(search) && !all.assetsAudio.Contains(item))
                        {
                            all.assetsAudio.Add(item);
                        }
                    }
                }
                
            }
            else
            {
                all.assets2D = _context.Assets2D.ToList();
                all.assets3D = _context.Assets3D.ToList();
                all.assetsTools = _context.AssetsTools.ToList();
                all.assetsAudio = _context.AssetsAudio.ToList();
            }
            if (all.assets2D != null) {
                foreach (Asset2D model in all.assets2D)
                {
                    if (model.imagesId != null)
                    {
                        int elem = int.Parse(model.imagesId.Split(',').First());
                        var photo = _photoContext.AssetsPhotos.FirstOrDefault(z => z.Id == elem);
                        all.asset2dImages.Add(photo.ImageData);
                    }
                }
            }
            if (all.assets3D != null) {
                foreach (Asset3D model in all.assets3D)
                {
                    if (model.imagesId != null)
                    {
                        int elem = int.Parse(model.imagesId.Split(',').First());
                        var photo = _photoContext.AssetsPhotos.FirstOrDefault(z => z.Id == elem);
                        all.asset3dImages.Add(photo.ImageData);
                    }
                }
            }
            if (all.assetsAudio != null)
            {
                foreach (AssetAudio model in all.assetsAudio)
                {
                    if (model.imagesId != null)
                    {
                        int elem = int.Parse(model.imagesId.Split(',').First());
                        var photo = _photoContext.AssetsPhotos.FirstOrDefault(z => z.Id == elem);
                        all.assetAudioImages.Add(photo.ImageData);
                    }
                }
            }
            if (all.assetsTools != null) {
                foreach (AssetTools model in all.assetsTools)
                {
                    if (model.imagesId != null)
                    {
                        int elem = int.Parse(model.imagesId.Split(',').First());
                        var photo = _photoContext.AssetsPhotos.FirstOrDefault(z => z.Id == elem);
                        all.assetsToolsImages.Add(photo.ImageData);
                    }
                }
            }
            return View(all);
        }

        public ActionResult _2D(int Id) {
            var asset = _context.Assets2D.FirstOrDefault(z => z.Id == Id);
            AssetPhotosModel model = new AssetPhotosModel();
            model.asset = asset;
            var user_id = User.Identity.GetUserId();
            //var user_id = System.Web.Security.Membership.GetUser(User.Identity.Name).ProviderUserKey.ToString();
            var item = _itemContext.Assets.FirstOrDefault(z => z.assetId == model.asset.Id && z.assetType == "2D" && z.buyerId == user_id);
            if (item != null)
            {
                model.item = item;
            }
            //model.asset.Size = model.asset.assetZip.Count() / 1048576f;
            if (model.item != null)
            {
                
            }
            string[] str = asset.imagesId.Split(',');
            int[] ints = Array.ConvertAll(str, s => int.Parse(s));
            for (int i = 0; i < ints.Length; i++)
            {

                var photo = _photoContext.AssetsPhotos.AsEnumerable().FirstOrDefault(z => z.Id == ints[i]);
                model.photos.Add(photo.ImageData);
            }
            return View(model);
        }
        public ActionResult _3D(int Id)
        {
               
            var asset = _context.Assets3D.FirstOrDefault(z => z.Id == Id);
            AssetPhotosModel model = new AssetPhotosModel();
            model.asset = asset;
            string user_id = User.Identity.GetUserId();
            var item = _itemContext.Assets.FirstOrDefault(z => z.assetId == model.asset.Id && z.assetType == "3D" && z.buyerId == user_id);
            if (item != null)
            {
                model.item = item;
            }
            //model.asset.Size = model.asset.assetZip.Count() / 1048576f;
             
            //model.asset.Size = model.asset.assetZip.Count() / 1048576f;
            string[] str = asset.imagesId.Split(',');
            int[] ints = Array.ConvertAll(str, s => int.Parse(s));
            for (int i = 0; i < ints.Length; i++)
            {
                
                var photo = _photoContext.AssetsPhotos.AsEnumerable().FirstOrDefault(z => z.Id == ints[i]);
                model.photos.Add(photo.ImageData);
            }
            return View(model);
        }
        public ActionResult Tools(int Id)
        {
            var asset = _context.AssetsTools.FirstOrDefault(z => z.Id == Id);
            AssetPhotosModel model = new AssetPhotosModel();
            model.asset = asset;
            string user_id = User.Identity.GetUserId();
            var item = _itemContext.Assets.FirstOrDefault(z => z.assetId == model.asset.Id && z.assetType == "Tools" && z.buyerId == user_id);
            if (item != null)
            {
                model.item = item;
            }
            //model.asset.Size = model.asset.assetZip.Count() / 1048576f;
            string[] str = asset.imagesId.Split(',');
            int[] ints = Array.ConvertAll(str, s => int.Parse(s));
            for (int i = 0; i < ints.Length; i++)
            {

                var photo = _photoContext.AssetsPhotos.AsEnumerable().FirstOrDefault(z => z.Id == ints[i]);
                model.photos.Add(photo.ImageData);
            }
            return View(model);
        }
        public ActionResult Audio(int Id)
        {
            var asset = _context.AssetsAudio.FirstOrDefault(z => z.Id == Id);
            AssetPhotosModel model = new AssetPhotosModel();
            model.asset = asset;
            string user_id = User.Identity.GetUserId();
            var item = _itemContext.Assets.FirstOrDefault(z => z.assetId == model.asset.Id&& z.assetType == "Audio" && z.buyerId == user_id);
            if (item != null)
            {
                model.item = item;
            }
            //model.asset.Size = model.asset.assetZip.Count() / 1048576f;
            string[] str = asset.imagesId.Split(',');
            int[] ints = Array.ConvertAll(str, s => int.Parse(s));
            for (int i = 0; i < ints.Length; i++)
            {

                var photo = _photoContext.AssetsPhotos.AsEnumerable().FirstOrDefault(z => z.Id == ints[i]);

AssetStore/Views/Assets/AboutUs.cshtml
<h2>About Us</h2><hr />
<p>This web app was created by 4 students for subject Internet Technologies at Faculty for Computer Science and Engineering</p><br />
<p>The name of students are:</p>
<ul>
    <li>Andrej Subasik</li>
    <li>Hristijan Chaushoski</li>
    <li>Darko Filipcev</li>
    <li>Stefan Tofceski</li>
</ul>

AssetStore/Views/Assets/Audio.cshtml
@model AssetStore.Models.AssetPhotosModel

    <div>
        <h4>@Model.asset.Name</h4>
        <hr />
        <dl class="dl-horizontal">

            <dt>
                <label>Made by:</label>
            </dt>
            
            <dd>
                @Html.DisplayFor(model => model.asset.Publisher)
            </dd>
        </dl>
        <div id="main" class="row col-12">
            <div id="div1" class="row col-lg-12 col-xl-8 col-md-12 col-12">
                <div class="flex-column col-5 col-md-3 col-lg-2 image-holder" style="margin:0; display:inline">
                    @{
                        foreach (byte[] b in Model.photos)
                        {
                            var base64 = Convert.ToBase64String(b);
                            var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                            <img src="@imgSrc" width="86px" height="70px" style="padding:7px 0 8px 0; cursor:pointer"
                                 class="image-aside" />
                            <br />
                        }
                    }

                </div>
                <div class="col-6 col-md-3 col-lg-3" style="display:inline">
                    <img id="mainImage" width="500px" height="380px" style="padding:0" />
                </div>
                <br />
                

            </div>

            <div id="div2" class="row col-lg-12 col-xl-4 col-md-12 col-12">
                <div class="col-8 col-md-3" style="height:10%">
                    <label>Your Price:</label>
                    <br />
                    @Html.DisplayFor(model => model.asset.Price)
                    <label>€</label>

                </div>

                <div class="col-4 col-md-3" style="height:10%">

                    @{
                        if (User.Identity.IsAuthenticated)
                        {
                            var item = Model.item;
                            if (item != null)
                            {
                                if (item.isBought)
                                {
                                    <button style="width:124px;" class="btn btn-success" onclick="location.href='@Url.Action("MyAssets", "Account")'">
                                        View in My Assets
                                    </button>
                                }
                                else if (item.isInCart)
                                {
                                    <button style="width:124px;" class="btn btn-success" onclick="location.href='@Url.Action("Cart", "Account")'">
                                        View in Cart
                                    </button>
                                }
                            }
                            else
                            {
                                <button style="width:124px;" class="btn btn-success" onclick="location.href='@Url.Action("AddToCart", new { Id = Model.asset.Id, type = Model.asset.Type, })'">
                                    Add to Cart
                                </button>
                            }
                        }

                    }


                </div>
                <div class="col-12">
                    <h5>Details:</h5>
                    <label>Size:</label>
                    @Html.DisplayFor(model => model.asset.Size)
                    <label>MB</label><br />
                    <label>Released On:</label>
                    @Html.DisplayFor(model => model.asset.ReleaseDate)
                    <label style="margin:0 auto">Description</label>
                    <p id="description">
                        @Model.asset.Description
                    </p>
                </div>
                <div class="col-12" style="float:left">
                    
                </div>
            </div>
        </div>
    </div>

    @section Scripts{
        <script>
    $(function () {
        var alt = $("#mainImage").attr("src");
        if (alt == undefined) {

            $("#mainImage").attr("src", $(".image-holder").children().first().attr("src"));
                }        
            });
            $(".image-aside").on("click", function() {
                $("#mainImage").attr("src", $(this).attr("src"));
            });
        </script>        
    }

AssetStore/Views/Assets/Downloads.cshtml
@Html.ActionLink("Download", "Download");

AssetStore/Views/Assets/HowToPublisher.cshtml
<head>
    <style>

    </style>
</head>

<h1>Sell Assets</h1>
<p>
    Whether you're a programmer, game designer, texture artist or 3D modeler, you’re welcome to share your creations with everybody in the Finki developer community!

    You can sell 3D models, editor extensions, audio and many other types of content. It’s easy – just submit your awesome creations to the Asset Store and we’ll take care of the rest. You can actually make enough money to fund your life and your game!

    Once your submission is reviewed, you are free to set your own price for the asset. You’ll receive a 70% cut of each sale, which we pay out monthly or quarterly, depending on your selected payment method. Don’t forget to read the default Customer EULA that covers end-user use of the assets you sell.
</p>
<h2>Submitting your content to Finki Asset Store:</h2>
<ol>
    <li>If you do not have Finki Asset Store account create one <a href="@Url.Action("Register", "Account")">here</a></li>
    <li>If you are not registered as Publisher do so by creating account <a href="@Url.Action("Publisher", "Account")">here</a></li>
    <li>Once you submit application for publisher an admin has to review it and decide whether to accept it or not</li>
    <li>Once accepted you can publish your asset by filling <a href="@Url.Action("Publish", "Assets")">this</a> form</li>
</ol>

AssetStore/Views/Assets/Index.cshtml
@model AssetStore.Models.AllAssets



@if (Model.assets2D != null)
{
    int i = -1;
    <div class="asset-holder text-center row" style="">
        @{

            foreach (var item in Model.assets2D)
            {
                try
                {
                    i++;
                    var base64 = Convert.ToBase64String(Model.asset2dImages[i]);
                    var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                    <div class="col-md-4 col-xl-3 col-sm-4 col-12 m-sm-4 m-lg-0 m-2" style="padding:0;" width="206px">
                        <img class=" p-lg-0 thumbnail" onclick="location.href= '@Url.Action("_2D", new { Id = item.Id })'" src="@imgSrc" width="240px" height="150px" style="padding:0; border-radius:4px;margin:0px;cursor:pointer;" />
                        <p>@item.Name</p>
                    </div>
                }
                catch (Exception e) { }
            }
            i=-1;
            foreach (var item in Model.assets3D)
            {
                try
                {
                    i++;
                    var base64 = Convert.ToBase64String(Model.asset3dImages[i]);
                    var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                    <div class="col-md-4 col-xl-3 col-sm-4 col-12 m-sm-4 m-lg-0 m-2" style="padding:0;" width="206px">
                        <img class="p-lg-0 thumbnail" onclick="location.href= '@Url.Action("_3D", new { Id = item.Id })'" src="@imgSrc" width="240px" height="150px" style="padding:0; border-radius:4px;margin:0px;cursor:pointer;" />
                        <p>@item.Name</p>
                    </div>
                }
                catch (Exception e) { }
            }
            i=-1;
            foreach (var item in Model.assetsAudio)
            {
                try
                {
                    i++;
                    var base64 = Convert.ToBase64String(Model.assetAudioImages[i]);
                    var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                    <div class="col-md-4 col-xl-3 col-sm-4 col-12 m-sm-4 m-lg-0 m-2" style="padding:0;" width="206px">
                        <img class="p-lg-0 thumbnail" onclick="location.href= '@Url.Action("Audio", new { Id = item.Id })'" src="@imgSrc" width="240px" height="150px" style="padding:0; border-radius:4px;margin:0px;cursor:pointer;" />
                        <p>@item.Name</p>
                    </div>
                }
                catch (Exception e) { }
            }
            i=-1;
            foreach (var item in Model.assetsTools)
            {
                try
                {
                    i++;
                    var base64 = Convert.ToBase64String(Model.assetsToolsImages[i]);
                    var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                    <div class="col-md-4 col-xl-3 col-sm-4 col-12 m-sm-4 m-lg-0 m-2" style="padding:0;" width="206px">
                        <img class="p-xl-0 thumbnail" onclick="location.href= '@Url.Action("Tools", new { Id = item.Id })'" src="@imgSrc" width="240px" height="150px" style="padding:0; border-radius:4px;margin:0px;cursor:pointer;" />
                        <p>@item.Name</p>
                    </div>
                }
                catch (Exception e) { }
            }
        }
    </div>
}


<!--</table>-->
@section Scripts{
    <script>
    $(function () {
        if (window.innerWidth >= 576 && window.innerWidth < 768) {
            $(".thumbnail").css("padding", "0 1.25rem 0 1.25rem");
        }
        $(window).resize(function () {
            if (window.innerWidth >= 576 && window.innerWidth < 768) {
                $(".thumbnail").css("padding", "0 1.25rem 0 1.25rem");
            }
            else {
                $(".thumbnail").css("padding", "0");
            }
        });
    });

    $('body').css({
            position: 'relative',
            top: '200px',
        });
        
    </script>

}

AssetStore/Views/Assets/NotAPublisher.cshtml
    <h2>
        Publisher Administration
    </h2>
    <hr />
    <h4>No Access</h4>
    <p>
        You are not registered as Finki Asset Store Publisher.
    </p>
    <ul>
        <li><a href="@Url.Action("LogIn", "Account")">Login as different user.</a></li>
        <li><a href="@Url.Action("HowToPublisher", "Assets")">How to become a publisher and submit content.</a></li>
        <li><a href="@Url.Action("Publisher", "Account")">Create new Finki Asset Store Publisher.</a></li>
    </ul>
@section Scripts{
    <script>
        $('body').css({
            position: 'relative',
            top: '50px',

        });
    </script>
}

AssetStore/Views/Assets/Publish.cshtml
@model AssetStore.Models.AssetImages

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")


@using (Html.BeginForm("Publish", "Assets", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Publish Asset</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.asset.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.asset.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.asset.Name, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.asset.Platform, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.asset.Platform, new SelectList(new string[] { "Windows", "Mac OS", "Linux", "Android", "iOS", "Web GL" }), "-- Select platform --", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.asset.Platform, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.asset.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.asset.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.asset.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.asset.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.asset.Type, new SelectList(new string[] { "2D", "3D", "Tools", "Audio" }), "-- Select type", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.asset.Type, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.asset.Description, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.asset.Description, htmlAttributes: new { @class = "control-label col-md-4" })
                <br />
                @Html.ValidationMessageFor(model => model.asset.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Files, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-offset-2 col-md-10">
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.Files, new { type = "file", multiple = "multiple" })
                    <br />
                    @Html.ValidationMessageFor(model => model.Files, "" , new { @class = "text-danger" })
                </div>
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.File, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-offset-2 col-md-10">
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.File, new { type = "file" })
                    <br />
                    @Html.ValidationMessageFor(model => model.File, "" , new { @class = "text-danger" })
                </div>
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

AssetStore/Views/Assets/Tools.cshtml
@model AssetStore.Models.AssetPhotosModel

<div>
    <h4>@Model.asset.Name</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            <label>Made by:</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.asset.Publisher)
        </dd>
    </dl>
    <div id="main" class="row col-12">
        <div id="div1" class="row col-lg-12 col-xl-8 col-md-12 col-12">
            <div class="flex-column col-5 col-md-3 col-lg-2 image-holder" style="margin:0; display:inline">
                @{
                    foreach (byte[] b in Model.photos)
                    {
                        var base64 = Convert.ToBase64String(b);
                        var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                        <img src="@imgSrc" width="86px" height="70px" style="padding:7px 0 8px 0; cursor:pointer"
                             class="image-aside" />
                        <br />
                    }
                }

            </div>
            <div class="col-6 col-md-3 col-lg-3" style="display:inline">
                <img id="mainImage" width="500px" height="380px" style="padding:0" />
            </div>
            <br />


        </div>

        <div id="div2" class="row col-lg-12 col-xl-4 col-md-12 col-12">
            <div class="col-8 col-md-3" style="height:10%">
                <label>Your Price:</label>
                <br />
                @Html.DisplayFor(model => model.asset.Price)
                <label>€</label>

            </div>

            <div class="col-4 col-md-3" style="height:10%">

                @{
                    if (User.Identity.IsAuthenticated)
                    {
                        var item = Model.item;
                        if (item != null)
                        {
                            if (item.isBought)
                            {
                                <button style="width:124px;" class="btn btn-success" onclick="location.href='@Url.Action("MyAssets", "Account")'">
                                    View in My Assets
                                </button>
                            }
                            else if (item.isInCart)
                            {
                                <button style="width:124px;" class="btn btn-success" onclick="location.href='@Url.Action("Cart", "Account")'">
                                    View in Cart
                                </button>
                            }
                        }
                        else
                        {
                            <button style="width:124px;" class="btn btn-success" onclick="location.href='@Url.Action("AddToCart", new { Id = Model.asset.Id, type = Model.asset.Type, })'">
                                Add to Cart
                            </button>
                        }
                    }

                }


            </div>
            <div class="col-12">
                <h5>Details:</h5>
                <label>Size:</label>
                @Html.DisplayFor(model => model.asset.Size)
                <label>MB</label><br />
                <label>Released On:</label>
                @Html.DisplayFor(model => model.asset.ReleaseDate)
                <label style="margin:0 auto">Description</label>
                <p id="description">
                    @Model.asset.Description
                </p>
            </div>
            <div class="col-12" style="float:left">

            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
    $(function () {
        var alt = $("#mainImage").attr("src");
        if (alt == undefined) {

            $("#mainImage").attr("src", $(".image-holder").children().first().attr("src"));
                }
            });
            $(".image-aside").on("click", function() {
                $("#mainImage").attr("src", $(this).attr("src"));
            });
    </script>
}

AssetStore/Views/Assets/View.cshtml
@model AssetStore.Models.Picture
@{
    var base64 = Convert.ToBase64String(Model.ImageData);
    var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
}

<img src="@imgSrc" />